[phases.setup]
nixPkgs = ["php83", "composer", "nodejs_20", "npm"]

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "php artisan optimize",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"